### ISSUE TITLE
[Bug] issue not showing up

### ISSUE THREAD

**Issue by M1ChaeL756** [fabbe50/FogOverridesIssues#2]
**Describe the bug**
Hello! I recently downloaded the fogoverrides mod, but when i go in the config folder of minecraft, there is nothing about fogoverrides there so i cant change the settings

**To Reproduce**
1. Go to '%appdata%'
2. Click on 'minecraft'
3. Scroll down to 'configs'
4. click on configs and theres nothing there about fogoverrides

**Expected behavior**
i expected to see a folder about fogoverrides, then if i go in the folder i expected to change it 

**Screenshots**
there are some other mods in the config folder, i dont want to share that sorry

**Versions (please complete the following information):**
 - Minecraft Version: 1.19
 - Forge Version: ? if you mean fabric version thats 1.14.6
 - Mod Version: 1.19 -1.1.2

**Additional context**
none other things

**Comment by fabbe50** [comment]
The mod is Forge only, it doesn't run on Fabric and I have no intention to port it to fabric as of now. Sorry for the inconvenience!

**Comment by ghost** [comment]
Alternatives for fabric:

https://www.curseforge.com/minecraft/mc-mods/see-through-lava-water
https://www.curseforge.com/minecraft/mc-mods/nofog

Neither of these are as good so ymmv.
